#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v9
# autospec commit: 658bd0d
#
Name     : libeconf
Version  : 0.6.3
Release  : 22
URL      : https://github.com/openSUSE/libeconf/archive/v0.6.3/libeconf-0.6.3.tar.gz
Source0  : https://github.com/openSUSE/libeconf/archive/v0.6.3/libeconf-0.6.3.tar.gz
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : MIT
Requires: libeconf-bin = %{version}-%{release}
Requires: libeconf-lib = %{version}-%{release}
Requires: libeconf-license = %{version}-%{release}
Requires: libeconf-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libeconf
**libeconf** is a highly flexible and configurable library to parse and
manage key=value configuration files.
It reads configuration file snippets from different directories and builds
the final configuration file for the application from it.

%package bin
Summary: bin components for the libeconf package.
Group: Binaries
Requires: libeconf-license = %{version}-%{release}

%description bin
bin components for the libeconf package.


%package dev
Summary: dev components for the libeconf package.
Group: Development
Requires: libeconf-lib = %{version}-%{release}
Requires: libeconf-bin = %{version}-%{release}
Provides: libeconf-devel = %{version}-%{release}
Requires: libeconf = %{version}-%{release}

%description dev
dev components for the libeconf package.


%package dev32
Summary: dev32 components for the libeconf package.
Group: Default
Requires: libeconf-lib32 = %{version}-%{release}
Requires: libeconf-bin = %{version}-%{release}
Requires: libeconf-dev = %{version}-%{release}

%description dev32
dev32 components for the libeconf package.


%package lib
Summary: lib components for the libeconf package.
Group: Libraries
Requires: libeconf-license = %{version}-%{release}

%description lib
lib components for the libeconf package.


%package lib32
Summary: lib32 components for the libeconf package.
Group: Default
Requires: libeconf-license = %{version}-%{release}

%description lib32
lib32 components for the libeconf package.


%package license
Summary: license components for the libeconf package.
Group: Default

%description license
license components for the libeconf package.


%package man
Summary: man components for the libeconf package.
Group: Default

%description man
man components for the libeconf package.


%package staticdev
Summary: staticdev components for the libeconf package.
Group: Default
Requires: libeconf-dev = %{version}-%{release}

%description staticdev
staticdev components for the libeconf package.


%package staticdev32
Summary: staticdev32 components for the libeconf package.
Group: Default
Requires: libeconf-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the libeconf package.


%prep
%setup -q -n libeconf-0.6.3
cd %{_builddir}/libeconf-0.6.3
pushd ..
cp -a libeconf-0.6.3 build32
popd
pushd ..
cp -a libeconf-0.6.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712933711
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs
cd ../build32;
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libeconf
cp %{_builddir}/libeconf-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libeconf/fcc7730890cf59ca8a39456c72a6d63c599094d9 || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/econftool
/usr/bin/econftool

%files dev
%defattr(-,root,root,-)
/usr/include/libeconf.h
/usr/include/libeconf_ext.h
/usr/lib64/libeconf.so
/usr/lib64/pkgconfig/libeconf.pc
/usr/share/man/man3/libeconf.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libeconf.so
/usr/lib32/pkgconfig/32libeconf.pc
/usr/lib32/pkgconfig/libeconf.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libeconf.so.0.6.2
/usr/lib64/libeconf.so.0
/usr/lib64/libeconf.so.0.6.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libeconf.so.0
/usr/lib32/libeconf.so.0.6.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libeconf/fcc7730890cf59ca8a39456c72a6d63c599094d9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/econftool.8

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libeconf.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libeconf.a
